### ISSUE TITLE
Use in Vite/Vue3 possible?

### ISSUE THREAD

**Issue by cliqer** [juliandreas/vue-toggles#3]
Hi,
Is it possible to be used within vite that only supports vue 3 next libraries?
Receiving errors that I'm not capable to fix:
```
Uncaught (in promise) TypeError: selfHook.call is not a function
    at callSyncHook (vue.js:5980)
    at applyOptions (vue.js:5772)
    at finishComponentSetup (vue.js:6526)
    at setupStatefulComponent (vue.js:6454)
    at setupComponent (vue.js:6394)
    at mountComponent (vue.js:4230)
    at processComponent (vue.js:4206)
    at patch (vue.js:3869)
    at mountChildren (vue.js:4025)
    at mountElement (vue.js:3979)
````
Many Thanks

**Comment by juliandreas** [comment]
This is something I will definitely look into once Vue 3 is officially released. But at the moment I can only confirm it working with Vue 2.

**Comment by gterras** [comment]
Hi, any plans on this subject now that Vue3 is out?

**Comment by adi-works** [comment]
I wanted to use this great component with Vue 3, so I did some quick debugging. The reason it doesn't work is that it's being built with Vue 2, which bundles a Vue 2 helper code that conflicts with Vue 3 (which is expected). Once you build it with Vue 3, it removes the initial error (see: https://github.com/module-federation/module-federation-examples/issues/456). So for the time being, I ripped the source into my Vue 3 project and the component rendered, but the actual toggling didn't work. After having a quick look at the docs for breaking-changes, all I had to do to make it work again is declare the emitted events (see: https://v3.vuejs.org/guide/migration/emits-option.html#overview), like so:

```diff
export default {
  props: { /* ... */ },
+ emits: ["click"],
  // ...
}
```

**Comment by ishowman** [comment]
> I wanted to use this great component with Vue 3, so I did some quick debugging. The reason it doesn't work is that it's being built with Vue 2, which bundles a Vue 2 helper code that conflicts with Vue 3 (which is expected). Once you build it with Vue 3, it should remove the initial error (see: [module-federation/module-federation-examples#456](https://github.com/module-federation/module-federation-examples/issues/456)). So for the time being, I ripped the source into my Vue 3 project and the component rendered, but the actual toggling didn't work. After having a quick look at the docs for breaking-changes, all I had to do to make it work again is declare the emitted events (see: https://v3.vuejs.org/guide/migration/emits-option.html#overview), like so:
> 
> ```diff
> export default {
>   props: { /* ... */ },
> + emits: ["click"],
>   // ...
> }
> ```

could you offer a github repo to show how to mix vue2 and vue3?

**Comment by adi-works** [comment]
But I did. Use the snippet above.

**Comment by mihaileu** [comment]
@juliandreas do you have any plan for bump it to use vue3

**Comment by juliandreas** [comment]
@mihaileu Yes, but I can't say when.

Anyone is free to send a PR with a working vue3 solution though.

**Comment by adi-works** [comment]
@juliandreas Just add that one line of code. 🤨

> I wanted to use this great component with Vue 3, so I did some quick debugging. The reason it doesn't work is that it's being built with Vue 2, which bundles a Vue 2 helper code that conflicts with Vue 3 (which is expected). Once you build it with Vue 3, it removes the initial error (see: [module-federation/module-federation-examples#456](https://github.com/module-federation/module-federation-examples/issues/456)). So for the time being, I ripped the source into my Vue 3 project and the component rendered, but the actual toggling didn't work. After having a quick look at the docs for breaking-changes, all I had to do to make it work again is declare the emitted events (see: [v3.vuejs.org/guide/migration/emits-option.html#overview](https://v3.vuejs.org/guide/migration/emits-option.html#overview)), like so:
> 
> ```diff
> export default {
>   props: { /* ... */ },
> + emits: ["click"],
>   // ...
> }
> ```

**Comment by juliandreas** [comment]
You can now try the beta version of the vue 3 component.

Install with `npm i vue-toggles@3.0.0-beta.4`

The import looks like this at the moment `import VueToggles from "vue-toggles/src/VueToggles";`

I'm not sure why `import VueToggles from "vue-toggles";` doesn't work, but it can't find the component that way.

To clarify, this is the `main.js`:
```
import { createApp } from "vue";
import App from "./App.vue";
import VueToggles from "vue-toggles/src/VueToggles";

const app = createApp(App);

app.component("VueToggles", VueToggles);
app.mount("#app");
```

**Comment by naftis** [comment]
Easy fix but just to help other people; I had to use:
```ts
import VueToggles from "vue-toggles/src/VueToggles.vue";
```

**Comment by adi-works** [comment]
> Easy fix but just to help other people; I had to use:
> 
> ```ts
> import VueToggles from "vue-toggles/src/VueToggles.vue";
> ```

It's not enough.

**Comment by CreativeWarlock** [comment]
So is this vue-toggles@3.0.0-beta.4 another abandoned project?

**Comment by juliandreas** [comment]
@CreativeWarlock You are more than welcome to send a PR with any improvements you have.

**Comment by marverix** [comment]
Hello,
thank you for your work. I have forked repo and made version working with Vue 3 + used TS. 2 major changes:

* it's using `v-model` instead `value` + `click`
* it's using `defineComponent` method

https://github.com/marverix/vue-toggles/blob/master/src/VueToggles.vue

Feel free to use it however you want. I removed all builder config etc, because I didn't need it, as I'm using Vite config in my root Vue 3 project and letting Vite + TS to do the job. I also didn't want to spend more time on configuration.

**Comment by juliandreas** [comment]
I've added support for Vue 3. It's the latest `2.0.0` version.

**How to update:**
`npm install vue-toggles@latest`

**How to use:**
```javascript
import { VueToggles } from "vue-toggles";
```

```html
<VueToggles :value="example" @click="example = !example" />
```

It's all in the README. Let me know if you find any bugs or if anything is unclear 🙏🏼

**Comment by juliandreas** [comment]
I've added support for `v-model` in version `2.1.0`, by popular demand.

You can now use the component in either of the following ways:
```html
<VueToggles :value="example" @click="example = !example" />
```

Or:
```html
<VueToggles v-model="example" />
```

Sorry for the long wait. I'm closing this issue and consider it resolved.
