### ISSUE TITLE
Enhancement: Expose Value on Change Event for Better Interactivity

### ISSUE THREAD

**Issue by vivekp1118** [juliandreas/vue-toggles#32]
### Enhancement: Expose Value in `change` Event

**Description:**

It would be helpful if the `@change` event on `vue-toggles`  to get the new value of the toggle. This allows users to perform actions based on the updated state.

**Current Behavior:**

The `@change` event does not provide the new value, making it difficult to perform actions based on the toggle's state.

**Expected Behavior:**

The `@change` event should pass the new value of the toggle to the event handler. For example:

```vue
<VueToggles
  v-model="isAllSelected"
  name="isSelected" 
  class="p-switch"
  @change="onChangeAllSelected(value)" 
>

**Comment by juliandreas** [comment]
> making it difficult to perform actions based on the toggle's state

This can achieved using Vue's existing reactivity system.

https://vuejs.org/guide/essentials/watchers.html

**Comment by juliandreas** [comment]
> This allows users to perform actions based on the updated state.

What's wrong with using the `@click`?

**Comment by vivekp1118** [comment]
When using `@click`, it does not emit any value. If you want to trigger side effects or functions based on the component’s state, you would need to pass these effects as props. This approach can add extra props and make the side effects less dynamic. If you need to perform certain functions on state changes, this method won’t be sufficient.

For `watch`, if you have 10 different components each requiring different logic and different `v-modal`, you would need to register different watchers for each one. This approach is not very maintainable and makes the code less readable. Instead, using reactive properties for changes makes the code more concise and readable. Here’s an example:

```html
<PrettyCheck v-model="einvdocIsCustomerQRCode"
             class="p-switch"
             name="einvdocIsCustomerQRCode"
             @change="onChangeValue('einvdocIsCustomerQRCode')">
</PrettyCheck>

By using this approach, you can handle side effects more efficiently, and the code remains cleaner and easier to manage.

**Comment by juliandreas** [comment]
`click` doesn't emit a value because it's not that complicated to figure out what value it emits.
It can only be `true` or `false`. And you already have that value, since it's being passed in.

Adding a `@change` event that emits the new value doesn't provide any information that isn't already available through the v-model binding. If you need an event to tell you what value is being emitted for a boolean that you already have control over, you're probably overengineering it.
